name: Build Mango Finder

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CXXFLAGS: /utf-8
      CFLAGS: /utf-8
    steps:
      - uses: actions/checkout@v4
        # replace with the huggingface download
        # with:
        #   lfs: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.2.3
      - name: Install LLVM 18
        run: |
          Invoke-WebRequest -Uri "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/LLVM-18.1.8-win64.exe" -OutFile "LLVM-18.1.8-win64.exe"
          Start-Process -FilePath ".\LLVM-18.1.8-win64.exe" -ArgumentList "/S" -NoNewWindow -Wait
          echo "C:\Program Files\LLVM\bin" >> $env:GITHUB_PATH
        shell: pwsh
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Hugging Face Hub
        run: pip install huggingface_hub
      - name: Download Models from Hugging Face
        run: |
          python -c "
          from huggingface_hub import hf_hub_download
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='embedding.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='embedding_tokenizer.json', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='vision.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='vision_tokenizer.json', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='whisper-small-q8_0.bin', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ch_PP-OCRv4_det_infer.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ch_ppocr_mobile_v2.0_cls_infer.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ch_PP-OCRv4_rec_infer.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ppocr_keys_v1.txt', local_dir='./src-tauri/assets/model')
          "
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Clean Tauri WiX Cache
        run: |
          Remove-Item -Path "$env:LOCALAPPDATA\tauri\WixTools*" -Recurse -Force -ErrorAction SilentlyContinue
        shell: pwsh

      - name: Build Windows
        run: pnpm tauri build --target x86_64-pc-windows-msvc
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        # with:
        #   lfs: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Hugging Face Hub
        run: pip install huggingface_hub
      - name: Download Models from Hugging Face
        run: |
          python -c "
          from huggingface_hub import hf_hub_download
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='embedding.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='embedding_tokenizer.json', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='vision.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='vision_tokenizer.json', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='whisper-small-q8_0.bin', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ch_PP-OCRv4_det_infer.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ch_ppocr_mobile_v2.0_cls_infer.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ch_PP-OCRv4_rec_infer.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ppocr_keys_v1.txt', local_dir='./src-tauri/assets/model')
          "
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Build Linux
        run: pnpm tauri build --target x86_64-unknown-linux-gnu --bundles deb
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/*/*

  build-macos:
    runs-on: macos-14
    env:
      CFLAGS: -U__ARM_FEATURE_MATMUL_INT8
      MACOSX_DEPLOYMENT_TARGET: "10.15"
    steps:
      - uses: actions/checkout@v4
        # with:
        #   lfs: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin, x86_64-apple-darwin
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Hugging Face Hub
        run: pip install huggingface_hub
      - name: Download Models from Hugging Face
        run: |
          python -c "
          from huggingface_hub import hf_hub_download
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='embedding.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='embedding_tokenizer.json', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='vision.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='vision_tokenizer.json', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='whisper-small-q8_0.bin', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ch_PP-OCRv4_det_infer.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ch_ppocr_mobile_v2.0_cls_infer.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ch_PP-OCRv4_rec_infer.onnx', local_dir='./src-tauri/assets/model')
          hf_hub_download(repo_id='moyangzhan/mango-finder', filename='ppocr_keys_v1.txt', local_dir='./src-tauri/assets/model')
          "
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build macOS (Apple Silicon)
        run: pnpm tauri build --target aarch64-apple-darwin
      # Intel Mac build disabled - uncomment if needed for Intel Mac users
      # - name: Build macOS (Intel)
      #   run: pnpm tauri build --target x86_64-apple-darwin
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
            # src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg

  release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          echo "::debug::Previous tag found: '$PREVIOUS_TAG'"

          CHANGELOG_CONTENT=""
          GIT_LOG_COMMAND=""

          if [ -z "$PREVIOUS_TAG" ]; then
            GIT_LOG_COMMAND='git log --pretty=format:"* %s (%h)"'
            CHANGELOG_CONTENT=$(git log --pretty=format:"* %s (%h)")
          else
            GIT_LOG_COMMAND="git log --pretty=format:\"* %s (%h)\" $PREVIOUS_TAG..HEAD"
            CHANGELOG_CONTENT=$(git log --pretty=format:"* %s (%h)" $PREVIOUS_TAG..HEAD)
          fi
          echo "::debug::Executing command: $GIT_LOG_COMMAND"
          echo "::debug::Raw git log output:"
          echo "$CHANGELOG_CONTENT"
          echo "::debug::End of raw git log output."
          DELIMITER=$(openssl rand -hex 8) 
          echo "::debug::Writing to GITHUB_OUTPUT with delimiter $DELIMITER"
          printf "%s<<%s\n%s\n%s\n" "CHANGELOG" "$DELIMITER" "$CHANGELOG_CONTENT" "$DELIMITER" >> "$GITHUB_OUTPUT"
          echo "::debug::Finished writing to GITHUB_OUTPUT."
        shell: bash

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List Files
        run: find artifacts -type f | sort

      - name: Get existing release body
        id: existing_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BODY=$(gh release view "${{ github.ref_name }}" --json body -q '.body' 2>/dev/null || echo "")
          echo "found_body=${BODY}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build release body
        id: build_body
        env:
          EXISTING_BODY: ${{ steps.existing_release.outputs.found_body }}
          CHANGELOG: ${{ steps.changelog.outputs.CHANGELOG }}
        run: |
          {
            echo "$EXISTING_BODY"
            echo ""
            echo "---"
            echo ""
            echo "#### Changelog"
            echo "$CHANGELOG"
          } | sed '/^$/N;/^\n$/d' > body.md
          # Remove trailing blank lines
          sed -i -e :a -e '/^\n*$/{$d;N;ba' -e '}' body.md
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows-build/*.msi
            artifacts/linux-build/deb/*.deb
            # artifacts/linux-build/rpm/*.rpm
            # artifacts/linux-build/appimage/*.AppImage
            artifacts/macos-build/*.dmg
            # artifacts/macos-build/x86_64-apple-darwin/release/bundle/dmg/*.dmg
          name: Release ${{ github.ref_name }}
          body_path: body.md
          draft: false
          prerelease: false
